#pragma once

#include <JuceHeader.h>
#include <array>
#include <vector>

/**
 *  The core logic for the 16-step sequencer.
 *  Handles timing, pattern storage, and MIDI generation.
 */
class SequencerEngine : public juce::HighResolutionTimer
{
public:
    SequencerEngine();
    ~SequencerEngine() override;

    // --- Transport Control ---
    void play();
    void stop();
    void reset();
    bool isPlaying() const;

    // --- Configuration ---
    void setBpm(double newBpm);
    double getBpm() const;
    
    // --- Pattern Management ---
    struct Step
    {
        int noteOffset = 0; // relative to base note (-12 to +12)
        bool gate = false;  // is step active?
    };

    void setStep(int index, int noteOffset, bool gate);
    Step getStep(int index) const;

    void setBaseNote(int midiNoteNumber);
    int getBaseNote() const;

    // --- Callbacks ---
    /**
     *  Register a callback to receive MIDI messages generated by the engine.
     *  The UI or main component will subscribe to this to send data to devices.
     */
    using MidiCallback = std::function<void(const juce::MidiMessage&)>;
    void setMidiCallback(MidiCallback callback);
    
    /**
     *  Register a callback to receive playhead position updates (0-15).
     *  Use this to update the UI.
     */
    using StepCallback = std::function<void(int)>;
    void setStepCallback(StepCallback callback);

private:
    // --- juce::HighResolutionTimer Implementation ---
    void hiResTimerCallback() override;

    // --- Internal State ---
    std::array<Step, 16> pattern;
    int currentStep = 0;
    bool playing = false;
    double bpm = 120.0;
    int baseNote = 60; // C3

    // To prevent hanging notes, track the last note we played
    int lastNotePlayed = -1; 

    MidiCallback midiCallback;
    StepCallback stepCallback;

    void updateTimerInterval();
    void sendNoteOff();
    void advanceStep();
};
